// Date: 22.5.2013 16:56:28
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package deadspacemod.client.itemrenders;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DSModelLineGun extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
    ModelRenderer Shape34;
    ModelRenderer Shape35;
  
  public DSModelLineGun()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 119);
      Shape1.addBox(0F, 0F, 0F, 3, 2, 7);
      Shape1.setRotationPoint(0F, -3F, -2F);
      Shape1.setTextureSize(256, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 111);
      Shape2.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape2.setRotationPoint(0.5F, -1F, 2F);
      Shape2.setTextureSize(256, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0.0743572F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 108);
      Shape3.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape3.setRotationPoint(0.5F, -1F, 1.7F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 102);
      Shape4.addBox(0F, 0F, 0F, 3, 2, 3);
      Shape4.setRotationPoint(0F, 3F, 1.7F);
      Shape4.setTextureSize(256, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 92);
      Shape5.addBox(0F, 0F, 0F, 2, 2, 7);
      Shape5.setRotationPoint(0.5F, 3F, -5F);
      Shape5.setTextureSize(256, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 86);
      Shape6.addBox(0F, 0F, 0F, 1, 2, 3);
      Shape6.setRotationPoint(1F, -2F, -3F);
      Shape6.setTextureSize(256, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 79);
      Shape7.addBox(0F, 0F, 0F, 1, 4, 2);
      Shape7.setRotationPoint(1F, -1F, -4F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 75);
      Shape8.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape8.setRotationPoint(1F, 2.5F, -5.5F);
      Shape8.setTextureSize(256, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 72);
      Shape9.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape9.setRotationPoint(0F, 1F, -4.5F);
      Shape9.setTextureSize(256, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 68);
      Shape10.addBox(0F, 0F, 0F, 3, 2, 1);
      Shape10.setRotationPoint(0F, 0F, -3.5F);
      Shape10.setTextureSize(256, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 62);
      Shape11.addBox(0F, 0F, 0F, 7, 2, 3);
      Shape11.setRotationPoint(-2F, 0F, -7F);
      Shape11.setTextureSize(256, 128);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 57);
      Shape12.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape12.setRotationPoint(10F, -0.55F, -6.5F);
      Shape12.setTextureSize(256, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 20, 48);
      Shape13.addBox(0F, 0F, 0F, 5, 0, 4);
      Shape13.setRotationPoint(5F, 0.5F, -8F);
      Shape13.setTextureSize(256, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 10, 86);
      Shape14.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape14.setRotationPoint(5F, 0.45F, -8F);
      Shape14.setTextureSize(256, 128);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 14, 102);
      Shape15.addBox(0F, 0F, 0F, 2, 1, 4);
      Shape15.setRotationPoint(8F, 0.45F, -8F);
      Shape15.setTextureSize(256, 128);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 22, 86);
      Shape16.addBox(0F, 0F, 0F, 1, 1, 4);
      Shape16.setRotationPoint(-7F, 0.45F, -8F);
      Shape16.setTextureSize(256, 128);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 40, 48);
      Shape17.addBox(0F, 0F, 0F, 5, 0, 4);
      Shape17.setRotationPoint(-7F, 0.5F, -8F);
      Shape17.setTextureSize(256, 128);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 60, 48);
      Shape18.addBox(0F, 0F, 0F, 5, 0, 4);
      Shape18.setRotationPoint(-7F, 1.5F, -8F);
      Shape18.setTextureSize(256, 128);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 28, 102);
      Shape19.addBox(0F, 0F, 0F, 2, 1, 4);
      Shape19.setRotationPoint(-4F, 0.45F, -8F);
      Shape19.setTextureSize(256, 128);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 10, 116);
      Shape20.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape20.setRotationPoint(10F, 0.45F, -7.5F);
      Shape20.setTextureSize(256, 128);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 8, 53);
      Shape21.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape21.setRotationPoint(10F, 1F, -9.5F);
      Shape21.setTextureSize(256, 128);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 16, 117);
      Shape22.addBox(0F, 0F, 0F, 1, 0, 1);
      Shape22.setRotationPoint(10F, 2.5F, -9.8F);
      Shape22.setTextureSize(256, 128);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 22, 117);
      Shape23.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape23.setRotationPoint(10F, 1.5F, -9.8F);
      Shape23.setTextureSize(256, 128);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 26, 117);
      Shape24.addBox(0F, 0F, 0F, 1, 0, 1);
      Shape24.setRotationPoint(10F, -1F, -9.8F);
      Shape24.setTextureSize(256, 128);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 32, 117);
      Shape25.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape25.setRotationPoint(10F, -1F, -9.8F);
      Shape25.setTextureSize(256, 128);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 8, 57);
      Shape26.addBox(0F, 0F, 0F, 1, 2, 2);
      Shape26.setRotationPoint(-8F, -0.55F, -6.5F);
      Shape26.setTextureSize(256, 128);
      Shape26.mirror = true;
      setRotation(Shape26, 0F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 10, 113);
      Shape27.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape27.setRotationPoint(-8F, 0.45F, -7.5F);
      Shape27.setTextureSize(256, 128);
      Shape27.mirror = true;
      setRotation(Shape27, 0F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 16, 115);
      Shape28.addBox(0F, 0F, 0F, 1, 0, 1);
      Shape28.setRotationPoint(-8F, -1F, -9.8F);
      Shape28.setTextureSize(256, 128);
      Shape28.mirror = true;
      setRotation(Shape28, 0F, 0F, 0F);
      Shape29 = new ModelRenderer(this, 32, 115);
      Shape29.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape29.setRotationPoint(-8F, -1F, -9.8F);
      Shape29.setTextureSize(256, 128);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 0F, 0F);
      Shape30 = new ModelRenderer(this, 16, 53);
      Shape30.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape30.setRotationPoint(-8F, -0.5F, -9.5F);
      Shape30.setTextureSize(256, 128);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0F);
      Shape31 = new ModelRenderer(this, 26, 115);
      Shape31.addBox(0F, 0F, 0F, 1, 0, 1);
      Shape31.setRotationPoint(-8F, 2.5F, -9.8F);
      Shape31.setTextureSize(256, 128);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 22, 115);
      Shape32.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape32.setRotationPoint(-8F, 1.5F, -9.8F);
      Shape32.setTextureSize(256, 128);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0F);
      Shape33 = new ModelRenderer(this, 24, 53);
      Shape33.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape33.setRotationPoint(-8F, 1F, -9.5F);
      Shape33.setTextureSize(256, 128);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, 0F);
      Shape34 = new ModelRenderer(this, 0, 53);
      Shape34.addBox(0F, 0F, 0F, 1, 1, 2);
      Shape34.setRotationPoint(10F, -0.5F, -9.5F);
      Shape34.setTextureSize(256, 128);
      Shape34.mirror = true;
      setRotation(Shape34, 0F, 0F, 0F);
      Shape35 = new ModelRenderer(this, 0, 48);
      Shape35.addBox(0F, 0F, 0F, 5, 0, 4);
      Shape35.setRotationPoint(5F, 1.5F, -8F);
      Shape35.setTextureSize(256, 128);
      Shape35.mirror = true;
      setRotation(Shape35, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
    Shape34.render(f5);
    Shape35.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
}

