// Date: 18.5.2013 17:22:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package thecircle.deadspace.item.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DSModelPulseRifle extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
    ModelRenderer Shape34;
    ModelRenderer Shape35;
    ModelRenderer Shape36;
    ModelRenderer Shape37;
    ModelRenderer Shape38;
    ModelRenderer Shape39;
  
  public DSModelPulseRifle()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 107);
      Shape1.addBox(0F, 0F, 0F, 3, 6, 15);
      Shape1.setRotationPoint(-5F, 0F, 0F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0.7853982F);
      Shape2 = new ModelRenderer(this, 0, 77);
      Shape2.addBox(0F, 0F, 0F, 2, 6, 24);
      Shape2.setRotationPoint(-4.7F, 0.3F, -7F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0.7853982F);
      Shape3 = new ModelRenderer(this, 0, 56);
      Shape3.addBox(0F, 0F, 0F, 3, 6, 15);
      Shape3.setRotationPoint(-2.4F, 2F, 0F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, -0.7853982F);
      Shape4 = new ModelRenderer(this, 52, 77);
      Shape4.addBox(0F, 0F, 0F, 2, 6, 24);
      Shape4.setRotationPoint(-2F, 1.6F, -7F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, -0.7853982F);
      Shape5 = new ModelRenderer(this, 36, 56);
      Shape5.addBox(0F, 0F, 0F, 3, 6, 15);
      Shape5.setRotationPoint(-4.2F, -6F, 0F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 72, 47);
      Shape6.addBox(0F, 0F, 0F, 2, 6, 24);
      Shape6.setRotationPoint(-3.7F, -6F, -7F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 34);
      Shape7.addBox(0F, 0F, 0F, 8, 8, 14);
      Shape7.setRotationPoint(-2.5F, -5F, 17F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0.7853982F);
      Shape8 = new ModelRenderer(this, 58, 46);
      Shape8.addBox(0F, 0F, 0F, 2, 5, 5);
      Shape8.setRotationPoint(-3.4F, 6F, 17F);
      Shape8.setTextureSize(128, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0.7853982F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 50, 48);
      Shape9.addBox(0F, 0F, 0F, 2, 6, 2);
      Shape9.setRotationPoint(-3.4F, 5F, 23F);
      Shape9.setTextureSize(128, 128);
      Shape9.mirror = true;
      setRotation(Shape9, -0.7853982F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 28);
      Shape10.addBox(0F, 0F, 0F, 3, 2, 4);
      Shape10.setRotationPoint(-3.9F, 9F, 19F);
      Shape10.setTextureSize(128, 128);
      Shape10.mirror = true;
      setRotation(Shape10, -0.7853982F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 14, 29);
      Shape11.addBox(0F, 0F, 0F, 3, 3, 2);
      Shape11.setRotationPoint(-3.9F, 12.6F, 20F);
      Shape11.setTextureSize(128, 128);
      Shape11.mirror = true;
      setRotation(Shape11, 0.4537856F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 36, 113);
      Shape12.addBox(0F, 0F, 0F, 2, 0, 15);
      Shape12.setRotationPoint(0.8F, 3F, 27F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 70, 113);
      Shape13.addBox(0F, 0F, 0F, 2, 0, 15);
      Shape13.setRotationPoint(-7.89F, 3F, 27F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 21);
      Shape14.addBox(0F, 0F, 0F, 0, 5, 2);
      Shape14.setRotationPoint(-0.9F, 4F, 25F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, -0.7853982F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 4, 21);
      Shape15.addBox(0F, 0F, 0F, 0, 5, 2);
      Shape15.setRotationPoint(-3.9F, 4F, 25F);
      Shape15.setTextureSize(128, 128);
      Shape15.mirror = true;
      setRotation(Shape15, -0.7853982F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 8, 23);
      Shape16.addBox(0F, 0F, 0F, 0, 4, 1);
      Shape16.setRotationPoint(-0.9F, 7F, 22F);
      Shape16.setTextureSize(128, 128);
      Shape16.mirror = true;
      setRotation(Shape16, -0.7853982F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 10, 23);
      Shape17.addBox(0F, 0F, 0F, 0, 4, 1);
      Shape17.setRotationPoint(-3.9F, 7F, 22F);
      Shape17.setTextureSize(128, 128);
      Shape17.mirror = true;
      setRotation(Shape17, -0.7853982F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 14, 25);
      Shape18.addBox(0F, 0F, 0F, 0, 1, 3);
      Shape18.setRotationPoint(-3.4F, 8F, 21F);
      Shape18.setTextureSize(128, 128);
      Shape18.mirror = true;
      setRotation(Shape18, -0.4014257F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 14, 21);
      Shape19.addBox(0F, 0F, -3F, 0, 1, 3);
      Shape19.setRotationPoint(-1.4F, 11.3F, 25.9F);
      Shape19.setTextureSize(128, 128);
      Shape19.mirror = true;
      setRotation(Shape19, -0.7732158F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 20, 25);
      Shape20.addBox(0F, 0F, -3F, 0, 1, 3);
      Shape20.setRotationPoint(-3.4F, 11.3F, 25.9F);
      Shape20.setTextureSize(128, 128);
      Shape20.mirror = true;
      setRotation(Shape20, -0.7732118F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 24, 30);
      Shape21.addBox(0F, 0F, 0F, 0, 1, 3);
      Shape21.setRotationPoint(-1.4F, 8F, 21F);
      Shape21.setTextureSize(128, 128);
      Shape21.mirror = true;
      setRotation(Shape21, -0.4014257F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 72, 32);
      Shape22.addBox(0F, 0F, 0F, 2, 1, 14);
      Shape22.setRotationPoint(-3.4F, 11F, 24.4F);
      Shape22.setTextureSize(128, 128);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 54, 36);
      Shape23.addBox(0F, 0F, 0F, 0, 1, 9);
      Shape23.setRotationPoint(-7F, 3F, 27F);
      Shape23.setTextureSize(128, 128);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 54, 26);
      Shape24.addBox(0F, 0F, 0F, 0, 1, 9);
      Shape24.setRotationPoint(2F, 3F, 27F);
      Shape24.setTextureSize(128, 128);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 12, 23);
      Shape25.addBox(0F, 0F, 0F, 0, 4, 1);
      Shape25.setRotationPoint(-7F, 3.7F, 41F);
      Shape25.setTextureSize(128, 128);
      Shape25.mirror = true;
      setRotation(Shape25, 0.7853982F, 3.141593F, 0F);
      Shape26 = new ModelRenderer(this, 20, 20);
      Shape26.addBox(0F, 0F, 0F, 0, 4, 1);
      Shape26.setRotationPoint(-7F, 3.7F, 35.2F);
      Shape26.setTextureSize(128, 128);
      Shape26.mirror = true;
      setRotation(Shape26, 0.7853982F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 8, 18);
      Shape27.addBox(0F, 0F, 0F, 0, 4, 1);
      Shape27.setRotationPoint(2F, 3.7F, 41F);
      Shape27.setTextureSize(128, 128);
      Shape27.mirror = true;
      setRotation(Shape27, 0.7853982F, 3.141593F, 0F);
      Shape28 = new ModelRenderer(this, 10, 18);
      Shape28.addBox(0F, 0F, 0F, 0, 4, 1);
      Shape28.setRotationPoint(2F, 3.7F, 35.2F);
      Shape28.setTextureSize(128, 128);
      Shape28.mirror = true;
      setRotation(Shape28, 0.7853982F, 0F, 0F);
      Shape29 = new ModelRenderer(this, 30, 26);
      Shape29.addBox(0F, 0F, 0F, 0, 7, 1);
      Shape29.setRotationPoint(-7F, 6F, 38.7F);
      Shape29.setTextureSize(128, 128);
      Shape29.mirror = true;
      setRotation(Shape29, 0F, 3.141593F, 0.5410521F);
      Shape30 = new ModelRenderer(this, 32, 26);
      Shape30.addBox(0F, 0F, 0F, 0, 7, 1);
      Shape30.setRotationPoint(2F, 6F, 37.5F);
      Shape30.setTextureSize(128, 128);
      Shape30.mirror = true;
      setRotation(Shape30, 0F, 0F, 0.5205006F);
      Shape31 = new ModelRenderer(this, 0, 20);
      Shape31.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape31.setRotationPoint(-3.2F, -7F, -7F);
      Shape31.setTextureSize(128, 128);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 72, 21);
      Shape32.addBox(0F, 0F, 0F, 1, 1, 10);
      Shape32.setRotationPoint(-3F, -6F, 19F);
      Shape32.setTextureSize(128, 128);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0F);
      Shape33 = new ModelRenderer(this, 40, 12);
      Shape33.addBox(0F, 0F, 0F, 2, 0, 14);
      Shape33.setRotationPoint(-3.5F, -6F, 17F);
      Shape33.setTextureSize(128, 128);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, 0F);
      Shape34 = new ModelRenderer(this, 6, 19);
      Shape34.addBox(0F, 0F, 0F, 1, 2, 0);
      Shape34.setRotationPoint(-3F, -8F, 17F);
      Shape34.setTextureSize(128, 128);
      Shape34.mirror = true;
      setRotation(Shape34, 0F, 0F, 0F);
      Shape35 = new ModelRenderer(this, 4, 20);
      Shape35.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape35.setRotationPoint(-3.8F, -6.9F, 31F);
      Shape35.setTextureSize(128, 128);
      Shape35.mirror = true;
      setRotation(Shape35, 0F, 0F, -0.3141593F);
      Shape36 = new ModelRenderer(this, 2, 20);
      Shape36.addBox(0F, 0F, 0F, 1, 1, 0);
      Shape36.setRotationPoint(-2.2F, -7.2F, 31F);
      Shape36.setTextureSize(128, 128);
      Shape36.mirror = true;
      setRotation(Shape36, 0F, 0F, 0.3141593F);
      Shape37 = new ModelRenderer(this, 0, 19);
      Shape37.addBox(0F, 0F, 0F, 2, 1, 0);
      Shape37.setRotationPoint(0.8F, 2F, 42F);
      Shape37.setTextureSize(128, 128);
      Shape37.mirror = true;
      setRotation(Shape37, 0F, 0F, 0F);
      Shape38 = new ModelRenderer(this, 0, 18);
      Shape38.addBox(0F, 0F, 0F, 2, 1, 0);
      Shape38.setRotationPoint(-7.9F, 2F, 42F);
      Shape38.setTextureSize(128, 128);
      Shape38.mirror = true;
      setRotation(Shape38, 0F, 0F, 0F);
      Shape39 = new ModelRenderer(this, 72, 3);
      Shape39.addBox(0F, 0F, 0F, 1, 1, 17);
      Shape39.setRotationPoint(-2.9F, 9F, 2F);
      Shape39.setTextureSize(128, 128);
      Shape39.mirror = true;
      setRotation(Shape39, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
    Shape34.render(f5);
    Shape35.render(f5);
    Shape36.render(f5);
    Shape37.render(f5);
    Shape38.render(f5);
    Shape39.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
}

